this.listaProductos.push(new Producto().nuevoProducto(1,"Azúcar Moreno",17,9,,,,"Azucarera");
this.listaProductos.push(new Producto().nuevoProducto(2,"pan",4,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(3,"Nata",17,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(4,"Mantequilla",25,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(5,"Zanahorias",10,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(6,"Soja",20,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(7,"Trigo",2,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(8,"Tortitas",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(9,"Galleta",51,0,,,,"Panadería");
this.listaProductos.push(new Producto().nuevoProducto(10,"Bacon",240,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(11,"Huevos",20,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(12,"Azúcar blanco",34,2,,,,"Azucarera");
this.listaProductos.push(new Producto().nuevoProducto(13,"Añil",120,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(14,"Maíz",5,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(15,"Palomitas",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(16,"Queso",51,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(17,"Caña de azúcar",30,9,"SILO","S",9,"Azucarera");
this.listaProductos.push(new Producto().nuevoProducto(18,"Leche",60,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(19,"Tarta de Zanahoria",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(20,"Huevos con bacon",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(22,"Manzana",840,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(23,"Calabaza",5,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(24,"Pan de maíz",25,2,,,,);
this.listaProductos.push(new Producto().nuevoProducto(25,"Lana",420,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(26,"Tarta de calabaza",102,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(27,"Jersey",102,1,,,,);
this.listaProductos.push(new Producto().nuevoProducto(28,"Hamburguesa",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(29,"Tarta de Bacon",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(30,"Jersey azul",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(32,"Gorro azul de lana",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(33,"Almíbar",76,23,,,,"Azucarera");
this.listaProductos.push(new Producto().nuevoProducto(34,"Pastel de Zanahoria",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(35,"Palomitas con mantequilla",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(36,"Frambuesa",1080,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(37,"Pastel de nata",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(38,"Cereza",1620,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(39,"Pastel de bayas",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(40,"Lingote de plata",480,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(41,"Pastel de Queso",204,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(42,"Palomitas con chile",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(43,"Chile",240,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(44,"Lingote de platino",960,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(45,"Zumo de Zanahoria",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(46,"Magdalena de mora",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(47,"Magdalena de frambuesa",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(48,"Lingote de oro",720,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(49,"Hamburguesa de pescado",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(50,"Pescado",120,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(51,"Zumo de manzana",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(52,"Gratinado de pescado",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(53,"Tarta de manzana",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(54,"Mora",2040,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(55,"Zumo de cereza",127,1,,,,);
this.listaProductos.push(new Producto().nuevoProducto(56,"Tomate",360,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(57,"Helado de vainilla",102,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(58,"Zumo de tomate",76,2,,,,);
this.listaProductos.push(new Producto().nuevoProducto(59,"Leche de cabra",480,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(60,"Queso de cabra",76,4,,,,);
this.listaProductos.push(new Producto().nuevoProducto(61,"Polo de Cereza",153,5,,,,);
this.listaProductos.push(new Producto().nuevoProducto(62,"Pizza",12,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(63,"Tomates asados",76,3,,,,);
this.listaProductos.push(new Producto().nuevoProducto(64,"Fresa",480,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(65,"Helado de fresa",204,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(66,"Tarta de feta",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(67,"Mermelada de manzana",306,1,,,,);
this.listaProductos.push(new Producto().nuevoProducto(68,"Patata",220,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(69,"Patata asada",29,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(70,"Pastel de chocolate",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(71,"Gratinado de bacon",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(72,"Carbón refinado",360,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(73,"Cacao",1800,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(74,"Lingote de hierro",420,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(75,"Pastel de fresas",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(76,"Zumo de bayas",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(77,"Mermelada de Frambuesa",357,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(78,"Pizza picante",15,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(79,"Mermelada de cereza",357,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(80,"Pastelitos de patata",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(81,"Gratinado de carne",85,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(82,"Pan de patata",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(83,"Mermelada de mora",348,1,,,,);
this.listaProductos.push(new Producto().nuevoProducto(84,"Helado de chocolate",127,4,,,,);
this.listaProductos.push(new Producto().nuevoProducto(85,"Pulsera",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(86,"Collar",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(87,"Pescado y patatas",76,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(88,"Café Expreso",5,3,,,,"Cafetería");
this.listaProductos.push(new Producto().nuevoProducto(89,"Tela de algodón",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(90,"Chaparreras de lana",76,,,,,"Coser");
this.listaProductos.push(new Producto().nuevoProducto(92,"Camisa de algodón",38,,,,,"Coser");
this.listaProductos.push(new Producto().nuevoProducto(93,"Granos de café",2500,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(94,"Café con leche",10,0,,,,"Cafetería");
this.listaProductos.push(new Producto().nuevoProducto(95,"Pulsera metálica",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(96,"Vestido violeta",114,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(97,"Palomitas con chocolate",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(98,"Café Moca",15,,,,,"Cafetería");
this.listaProductos.push(new Producto().nuevoProducto(99,"Langosta",500,22,,,,);
this.listaProductos.push(new Producto().nuevoProducto(100,"Moca con frambuesa",30,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(101,"Pizza de Marisco",12,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(102,"Sopa de langosta",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(103,"Sopa de tomate",76,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(104,"Chocolate caliente",25,,,,,"Cafetería");
this.listaProductos.push(new Producto().nuevoProducto(105,"Miel",17,4,,,,);
this.listaProductos.push(new Producto().nuevoProducto(106,"Tarta de manzana y miel",200,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(108,"Brocheta de langosta",34,,,,,"Barbacoa");
this.listaProductos.push(new Producto().nuevoProducto(109,"Panal",30,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(110,"Pastel de manzana y miel",170,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(112,"Bufanda roja",127,,,,,"Telar");
this.listaProductos.push(new Producto().nuevoProducto(113,"Sopa de calabaza",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(114,"Palomitas con miel",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(115,"Algodón",150,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(116,"Mermelada de fresa",382,1,,,,);
this.listaProductos.push(new Producto().nuevoProducto(119,"Cera de abejas",45,7,,,,"Miel");
this.listaProductos.push(new Producto().nuevoProducto(121,"Vela de fresa",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(123,"Vela de frambuesa",89,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(124,"Manzana caramelizada",102,5,,,,);
this.listaProductos.push(new Producto().nuevoProducto(125,"Caramelos",76,6,,,,"Caramelos");
this.listaProductos.push(new Producto().nuevoProducto(127,"Sopa de pescado",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(128,"Almohada",155,,,,,"Coser");
this.listaProductos.push(new Producto().nuevoProducto(129,"Pluma de pato",180,1,,,,);
this.listaProductos.push(new Producto().nuevoProducto(131,"Salsa de soja",153,4,,,,);
this.listaProductos.push(new Producto().nuevoProducto(132,"Makis",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(133,"Arroz",45,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(134,"Aceitunas",1500,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(135,"Piruleta",612,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(136,"Lechuga",200,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(137,"Ensalada griega",76,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(138,"Manta",178,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(139,"Sushi de langosta",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(140,"Aceite de oliva",38,0,,,,"Salsas");
this.listaProductos.push(new Producto().nuevoProducto(141,"Gominolas",1224,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(142,"S.vegetal",34,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(143,"Ensalada con bacon",89,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(144,"Mayonesa",12,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(146,"Sushi de huevo",120,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(147,"Cóctel de marisco",102,0,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(148,"S.de Bacon",85,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(149,"Smoothie de bayas",63,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(150,"S.de huevo",68,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(151,"Smoothie verde",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(152,"Limón",1440,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(154,"Cuajada de limón",21,,,,,"Salsas");
this.listaProductos.push(new Producto().nuevoProducto(156,"Pasta fresca",15,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(157,"Ensalada de pasta",127,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(158,"Tarta de limón",114,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(159,"Salsa de tomate",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(160,"Tostada con miel",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(161,"Pastel de limón",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(162,"Smoothie de Yogur",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(164,"Sombrero de Cloché",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(165,"Vela de limón",114,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(166,"Sombrero de copa",178,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(167,"Ñoquis",80,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(168,"Fideo de arroz",20,2,,,,"Pasta Máquina");
this.listaProductos.push(new Producto().nuevoProducto(169,"Sopa de fideos",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(170,"Sombrero de playa",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(171,"Mermelada de Naranja",433,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(172,"Naranja",1920,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(173,"Zumo de naranja",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(174,"Perrito caliente",30,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(175,"Cebolla a la parrilla",51,,,,,"Barbacoa");
this.listaProductos.push(new Producto().nuevoProducto(176,"Cebolla",300,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(177,"Sopa de cebolla",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(178,"Lasaña",100,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(179,"Tarta de melocotón",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(180,"Melocotón",1920,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(182,"Perrito de maíz",60,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(183,"Sorbete de naranja",178,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(184,"Salsa picante",17,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(185,"Sopa de patata",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(186,"Taco",45,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(187,"Taco de pescado",90,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(188,"Sopa de langosta",120,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(189,"Mermelada de melocotón",408,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(190,"Pasta con langosta",120,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(191,"Perrito con cebolla",75,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(192,"Té verde",30,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(194,"Hojas de té",390,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(195,"Té con leche",45,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(196,"Ensalada de frutas",102,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(197,"Quesudilla",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(198,"Té con miel",40,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(199,"Helado de melocotón",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(200,"Olivada",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(201,"Ramo rústico",45,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(202,"Rollito de verano",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(203,"Perrito vegetariano",45,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(204,"Chal de flores",76,,,,,"Telar");
this.listaProductos.push(new Producto().nuevoProducto(205,"Girasoles",90,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(206,"Pasta carbonara",150,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(207,"Uva",150,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(208,"Zumo de uva",127,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(209,"Helado de melocotón",153,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(210,"Ensalada veraniega",153,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(211,"Mermelada de uva",331,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(212,"Corona de flores",102,,,,,"Sombrerería");
this.listaProductos.push(new Producto().nuevoProducto(213,"Peonías",240,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(214,"Té con limón",20,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(216,"Nachos",75,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(217,"Batido mixto",25,,,,,"Licuadora");
this.listaProductos.push(new Producto().nuevoProducto(218,"Helado de menta",114,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(219,"Menta",180,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(220,"Maki grande",90,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(221,"Crudités",102,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(222,"Pimiento",270,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(223,"S.de cebolla y queso",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(224,"Latte Caramelo",15,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(225,"Café helado de plátano",20,,,,,"Cafetería");
this.listaProductos.push(new Producto().nuevoProducto(226,"Plátano",1620,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(227,"Pasta picante",90,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(228,"Pastel de frutas",153,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(229,"Té con naranja",40,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(230,"Sopa de pimiento",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(231,"Bizcocho de piña",63,,,,,"Pastelería");
this.listaProductos.push(new Producto().nuevoProducto(232,"Piña",30,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(233,"Zumo de piña",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(234,"S.de pepino",35,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(235,"Pepino",35,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(236,"Ramo de caramelos",20,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(237,"Pan de plátano",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(238,"Berenjena asada",34,,,,,"Barbacoa");
this.listaProductos.push(new Producto().nuevoProducto(239,"Berenjena",40,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(240,"Batido de pepino",34,,,,,"Licuadora");
this.listaProductos.push(new Producto().nuevoProducto(241,"Sopa de brocolí",63,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(242,"Pasta con brocolí",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(243,"Brocolí",80,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(245,"Zumo de sandía",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(246,"Sandía",300,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(247,"Té helado",30,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(248,"Tostada de queso de cabra",42,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(249,"Ramo delicado",30,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(250,"Tortitas de plátano",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(251,"Vela floral",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(252,"Mermelada de ciruela",255,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(253,"Ciruela",1920,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(254,"Banana split",178,,,,,"Heladería");
this.listaProductos.push(new Producto().nuevoProducto(255,"Té de menta",35,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(257,"Crocante de sésamo",51,,,,,"Caramelos");
this.listaProductos.push(new Producto().nuevoProducto(259,"Pastel de berenjena",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(260,"Fondue de Chocolate",25,,,,,"Fondue");
this.listaProductos.push(new Producto().nuevoProducto(261,"Chocolate",1020,9,,,,"Caramelos");
this.listaProductos.push(new Producto().nuevoProducto(262,"Té de manzana y jengibre",30,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(263,"Jengibre",150,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(265,"Fondue de bacon",30,,,,,"Fondue");
this.listaProductos.push(new Producto().nuevoProducto(266,"Pan de ajo",12,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(267,"Ensalada de remolacha",38,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(268,"Remolacha",40,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(269,"Chiles fritos",40,,,,,"Freiduría");
this.listaProductos.push(new Producto().nuevoProducto(270,"Salteado de tofu",75,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(271,"Sésamo",60,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(272,"Ensalada con setas",51,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(273,"Setas",20,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(274,"Brocheta de pescado",25,,,,,"Barbacoa");
this.listaProductos.push(new Producto().nuevoProducto(275,"Fondue de Queso",20,,,,,"Fondue");
this.listaProductos.push(new Producto().nuevoProducto(276,"Batido de cacao",34,,,,,"Licuadora");
this.listaProductos.push(new Producto().nuevoProducto(277,"Empanadas de manzana",20,,,,,"Freiduría");
this.listaProductos.push(new Producto().nuevoProducto(278,"Patatas con bacon",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(279,"S. Cacahuete y Mermelada",21,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(280,"Verduras asadas",21,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(281,"Pasta con setas",75,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(283,"Pescado picante",90,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(284,"Arroz frito",60,,,,,"Wok");
this.listaProductos.push(new Producto().nuevoProducto(285,"Dónut Clásico",15,,,,,"Donutería");
this.listaProductos.push(new Producto().nuevoProducto(286,"Dónut crocanti",30,,,,,"Donutería");
this.listaProductos.push(new Producto().nuevoProducto(287,"Dónut con crema",25,0,,,,"Donutería");
this.listaProductos.push(new Producto().nuevoProducto(288,"Dónut con bacon",30,,,,,"Donutería");
this.listaProductos.push(new Producto().nuevoProducto(289,"Dónut con virutas",20,,,,,"Donutería");
this.listaProductos.push(new Producto().nuevoProducto(290,"Mascarilla de miel",90,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(292,"Jabón exfoliante",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(293,"Loción de limón",75,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(294,"Jabón de miel",60,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(295,"Batido de ciruela",29,,,,,"Licuadora");
this.listaProductos.push(new Producto().nuevoProducto(296,"Pastel de setas",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(297,"Col",45,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(298,"Ramo de aniversario",20,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(299,"Sopa de col",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(300,"Lirios",90,9,"Silo","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(301,"Galleta de jengibre",25,,,,,"Panadería");
this.listaProductos.push(new Producto().nuevoProducto(302,"Dónut relleno",35,,,,,"Donutería");
this.listaProductos.push(new Producto().nuevoProducto(303,"Rollo de chocolate",76,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(304,"Cacahuetes garrapiñados",34,3,,,,"Caramelos");
this.listaProductos.push(new Producto().nuevoProducto(305,"Kinchi",255,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(306,"Velas coloridas",93,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(307,"Aperitvo salado",38,,,,,"Palomitera");
this.listaProductos.push(new Producto().nuevoProducto(308,"Pescado en lata",187,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(309,"Batido de cacahuete",85,,,,,"Heladería");
this.listaProductos.push(new Producto().nuevoProducto(310,"Cacahuetes",420,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(312,"Fruta deshidratada",153,,,,,"Conservas");
this.listaProductos.push(new Producto().nuevoProducto(313,"Zumo de maracuyá",38,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(314,"Ensalada de col",63,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(315,"Mermelada de maracuyá",272,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(316,"Tarta de chocolate",63,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(317,"Chocolatinas fritas",15,0,,,,"Freiduría");
this.listaProductos.push(new Producto().nuevoProducto(318,"Pimientos rellenos",17,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(319,"Vinagreta de maracuyá",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(320,"Ramo de verduras",15,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(321,"Pepinillos",204,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(322,"Batido de sésamo negro",38,,,,,"Licuadora");
this.listaProductos.push(new Producto().nuevoProducto(323,"Algodón de azúcar",25,,,,,"Caramelos");
this.listaProductos.push(new Producto().nuevoProducto(324,"Fideos con salsa de cacahuete",45,,,,,"Wok");
this.listaProductos.push(new Producto().nuevoProducto(325,"Sopa de setas",68,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(326,"Tarta de maracuyá",42,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(327,"Helado de sésamo",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(328,"Helado de coco",12,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(329,"Zumo de mango",42,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(330,"Batido tropical",34,,,,,"Licuadora");
this.listaProductos.push(new Producto().nuevoProducto(331,"Wrap de humus",25,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(332,"Humus",25,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(333,"Zumo de guayaba",46,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(334,"Pastel de granada",108,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(335,"Fudge de menta",150,,,,,"Fudge");
this.listaProductos.push(new Producto().nuevoProducto(336,"Fudge de chocolate",120,,,,,"Fudge");
this.listaProductos.push(new Producto().nuevoProducto(337,"Bolas de arroz",45,0,,,,"Sushi");
this.listaProductos.push(new Producto().nuevoProducto(338,"Yogur tropical",60,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(339,"Yogur",120,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(340,"Affogato",17,0,,,,"Heladería");
this.listaProductos.push(new Producto().nuevoProducto(341,"Estofado de chile",120,,,,,"Estofados");
this.listaProductos.push(new Producto().nuevoProducto(342,"Falafel",55,,,,,"Freiduría");
this.listaProductos.push(new Producto().nuevoProducto(343,"Fondue tropical",35,0,,,,"Fondue");
this.listaProductos.push(new Producto().nuevoProducto(344,"Tetera",240,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(345,"Compota de Guayaba",221,,,,,"Conservas");
this.listaProductos.push(new Producto().nuevoProducto(346,"Fudge de chile",170,0,,,,"Fudge");
this.listaProductos.push(new Producto().nuevoProducto(347,"Bolitas de coco",25,,,,,"Panadería");
this.listaProductos.push(new Producto().nuevoProducto(348,"Sorbete de frutas",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(349,"Samosa",75,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(350,"Maceta con flor",220,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(351,"Taza de arcilla",200,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(352,"Fudge de cacahuete",90,,,,,"Fudge");
this.listaProductos.push(new Producto().nuevoProducto(353,"Quiché de espárragos",102,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(354,"Espárragos a a la parrilla",63,0,,,,"Barbacoa");
this.listaProductos.push(new Producto().nuevoProducto(355,"Té de granada",35,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(356,"Tortilla de queso",90,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(358,"Haz de trigo",26,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(359,"Comida de cerdos",17,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(360,"Yogur de fresa",40,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(361,"Tortilla colorida",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(362,"Sopa de espárragos",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(363,"Fudge de limón",110,0,,,,"Fudge");
this.listaProductos.push(new Producto().nuevoProducto(364,"Tortilla de primavera",40,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(365,"Estofado de invierno",140,,,,,"Estofados");
this.listaProductos.push(new Producto().nuevoProducto(368,"Colgante floral",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(369,"Estofado de garbanzos",90,,,,,"Estofados");
this.listaProductos.push(new Producto().nuevoProducto(370,"Tortilla de arroz",120,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(371,"Cupcake",40,0,,,,"Cupcakes");
this.listaProductos.push(new Producto().nuevoProducto(372,"C.de guayaba",70,,,,,"Cupcakes");
this.listaProductos.push(new Producto().nuevoProducto(373,"C.Tropical",90,0,,,,"Cupcakes");
this.listaProductos.push(new Producto().nuevoProducto(374,"C.de galleta",120,0,,,,"Cupcakes");
this.listaProductos.push(new Producto().nuevoProducto(375,"Tortilla de patata",75,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(376,"Gofres normales",25,2,,,,);
this.listaProductos.push(new Producto().nuevoProducto(377,"G.con frutos rojos",35,,,,,"Gofrera");
this.listaProductos.push(new Producto().nuevoProducto(378,"Ramo colorido",20,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(379,"Gofres con chocolate",40,,,,,"Gofrera");
this.listaProductos.push(new Producto().nuevoProducto(380,"Gofres frutos rojos",35,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(381,"Ensalada de naranja",38,,,,,"Ensaladas");
this.listaProductos.push(new Producto().nuevoProducto(384,"Cerdo de chocolate",60,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(385,"Cabra de chocolate",90,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(386,"G.de huevos con bacon",45,,,,,"Gofrera");
this.listaProductos.push(new Producto().nuevoProducto(387,"Aceite esencial de limón",10,,,,,"Aceites esenciales");
this.listaProductos.push(new Producto().nuevoProducto(388,"Aceite esencial de menta",15,5,,,,"Aceites esenciales");
this.listaProductos.push(new Producto().nuevoProducto(389,"Bol de desayuno",50,,,,,"Gachas");
this.listaProductos.push(new Producto().nuevoProducto(390,"Avena",6,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(391,"Espárragos",360,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(392,"Coco",1440,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(393,"Guayaba",1440,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(394,"Garbanzos",60,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(395,"Mango",1920,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(396,"Maracuyá",60,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(397,"Granada",1620,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(398,"Ajos",30,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(399,"Arcilla",110,9,"SILO","S",9,);
this.listaProductos.push(new Producto().nuevoProducto(400,"Barritas de piña y coco",34,,,,,"Panadería");
this.listaProductos.push(new Producto().nuevoProducto(401,"Gachas con manzana",20,,,,,"Gachas");
this.listaProductos.push(new Producto().nuevoProducto(402,"Gachas dulces",45,,,,,"Gachas");
this.listaProductos.push(new Producto().nuevoProducto(403,"Gachas recién hechas",35,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(404,"Aceite esencial de jengibre",20,7,,,,);
this.listaProductos.push(new Producto().nuevoProducto(405,"Jabón lujoso",70,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(406,"Batido de vainilla",45,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(407,"Batido de moca",30,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(409,"Batido de frutas",35,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(415,"Aceite esencial de manzanilla",10,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(416,"Té de manzanilla",20,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(417,"Manzanilla",20,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(418,"Difusor fresco",20,0,,,,);
this.listaProductos.push(new Producto().nuevoProducto(419,"Almohada relajante",51,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(420,"Difusor relajante",25,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(421,"Perfume cítrico",15,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(422,"Arándanos",840,9,,"S",9,);
this.listaProductos.push(new Producto().nuevoProducto(423,"G.de Arándanos",42,,,,,);
this.listaProductos.push(new Producto().nuevoProducto(424,"Chutney de arándanos",163,,,,,);
this.listaProductos.push(new Producto().nuevoProducto();